/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigo;

import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;

/**
 *
 * @author hanni
 */
public class Materias extends javax.swing.JDialog {

    public Clip clip;
    public String ruta="/sonido/";
    
    public Materias(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(this);
        this.setTitle("Aprendix Space");
    }
    
        public void sonido(String archivo) {
        try {
            clip= AudioSystem.getClip();
            clip.open(AudioSystem.getAudioInputStream(getClass().getResourceAsStream(ruta+archivo+".wav")));
            clip.start();
        } catch (Exception ex) {
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonEcosistemas = new javax.swing.JButton();
        jButtonAtras = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jButtonAlimentacion = new javax.swing.JButton();
        jButtonNacimiento = new javax.swing.JButton();
        jButtonOrtografia = new javax.swing.JButton();
        jLabelBiologia = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jButtonGlosario = new javax.swing.JButton();
        jButtonOraciones = new javax.swing.JButton();
        jLabelEspaniol = new javax.swing.JLabel();
        jButtonMascota = new javax.swing.JButton();
        jLabelMasc = new javax.swing.JLabel();
        jLabelMascota = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonEcosistemas.setText("Ecosistemas");
        jButtonEcosistemas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonEcosistemasMouseEntered(evt);
            }
        });
        jButtonEcosistemas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEcosistemasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEcosistemas, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, -1, -1));

        jButtonAtras.setText("Atrás");
        jButtonAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonAtrasMouseEntered(evt);
            }
        });
        jButtonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 625, -1, -1));

        jButtonSalir.setText("Salir del programa");
        jButtonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonSalirMouseEntered(evt);
            }
        });
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(694, 625, -1, -1));

        jButtonAlimentacion.setText("Alimentación");
        jButtonAlimentacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonAlimentacionMouseEntered(evt);
            }
        });
        jButtonAlimentacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlimentacionActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAlimentacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, -1, -1));

        jButtonNacimiento.setText("Tipo de Nacimiento");
        jButtonNacimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonNacimientoMouseEntered(evt);
            }
        });
        jButtonNacimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNacimientoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 440, -1, -1));

        jButtonOrtografia.setText("Ortografía");
        jButtonOrtografia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonOrtografiaMouseEntered(evt);
            }
        });
        jButtonOrtografia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrtografiaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonOrtografia, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, -1, -1));

        jLabelBiologia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu/imagenes/ciencias.png"))); // NOI18N
        getContentPane().add(jLabelBiologia, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, -1, 440));

        jLabelTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu/imagenes/apre.png"))); // NOI18N
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, -1, -1));

        jButtonGlosario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu/imagenes/Glosario.png"))); // NOI18N
        jButtonGlosario.setText("Glosario");
        jButtonGlosario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonGlosarioMouseEntered(evt);
            }
        });
        jButtonGlosario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGlosarioActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGlosario, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, -1, -1));

        jButtonOraciones.setText("Oraciones");
        jButtonOraciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonOracionesMouseEntered(evt);
            }
        });
        jButtonOraciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOracionesActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonOraciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, -1, -1));

        jLabelEspaniol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/espaniol.png"))); // NOI18N
        getContentPane().add(jLabelEspaniol, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 230, -1));

        jButtonMascota.setText("Inglés");
        jButtonMascota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonMascotaMouseEntered(evt);
            }
        });
        jButtonMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMascotaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 360, -1, -1));
        getContentPane().add(jLabelMasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 410, 30, 20));

        jLabelMascota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu/imagenes/ingles.png"))); // NOI18N
        getContentPane().add(jLabelMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 190, 230, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        sonido("boton_1");
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtrasActionPerformed
        sonido("boton_1");
        this.setVisible(false);
    }//GEN-LAST:event_jButtonAtrasActionPerformed

    private void jButtonAtrasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAtrasMouseEntered
       sonido("Bur");
    }//GEN-LAST:event_jButtonAtrasMouseEntered

    private void jButtonSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSalirMouseEntered
        sonido("Bur");
    }//GEN-LAST:event_jButtonSalirMouseEntered

    private void jButtonEcosistemasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEcosistemasActionPerformed
        sonido("boton_1");
        Ecosistemas dialog = new Ecosistemas(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
        
    }//GEN-LAST:event_jButtonEcosistemasActionPerformed

    private void jButtonEcosistemasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEcosistemasMouseEntered
        sonido("Bur");
    }//GEN-LAST:event_jButtonEcosistemasMouseEntered

    private void jButtonAlimentacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlimentacionActionPerformed
        sonido("boton_1");
        Alimentacion dialog = new Alimentacion(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jButtonAlimentacionActionPerformed

    private void jButtonAlimentacionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAlimentacionMouseEntered
        // TODO add your handling code here:
        sonido("Bur");
    }//GEN-LAST:event_jButtonAlimentacionMouseEntered

    private void jButtonNacimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNacimientoActionPerformed
        // TODO add your handling code here:
        sonido("boton_1");
        Babys dialog = new Babys(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jButtonNacimientoActionPerformed

    private void jButtonNacimientoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNacimientoMouseEntered
        // TODO add your handling code here:
        sonido("Bur");
    }//GEN-LAST:event_jButtonNacimientoMouseEntered

    private void jButtonOracionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOracionesActionPerformed
        // TODO add your handling code here:
        sonido("boton_1");
        Oracion1 dialog = new Oracion1(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jButtonOracionesActionPerformed

    private void jButtonGlosarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGlosarioActionPerformed
        // TODO add your handling code here:
        sonido("hojas");
        Glosario dialog = new Glosario(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jButtonGlosarioActionPerformed

    private void jButtonGlosarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonGlosarioMouseEntered
        // TODO add your handling code here:
        sonido("hojas");
    }//GEN-LAST:event_jButtonGlosarioMouseEntered

    private void jButtonMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMascotaActionPerformed
        // TODO add your handling code here:
        sonido("boton_1");
        tamagochi2 dialog = new tamagochi2(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
        
        
    }//GEN-LAST:event_jButtonMascotaActionPerformed

    private void jButtonMascotaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMascotaMouseEntered
        // TODO add your handling code here:
        sonido("Bur");
    }//GEN-LAST:event_jButtonMascotaMouseEntered

    private void jButtonOracionesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonOracionesMouseEntered
        // TODO add your handling code here:
        sonido("Bur");
    }//GEN-LAST:event_jButtonOracionesMouseEntered

    private void jButtonOrtografiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrtografiaActionPerformed
        // TODO add your handling code here:
        sonido("boton_1");
        Ortografia1 dialog = new Ortografia1(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jButtonOrtografiaActionPerformed

    private void jButtonOrtografiaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonOrtografiaMouseEntered
        // TODO add your handling code here:
        sonido("Bur");
        
    }//GEN-LAST:event_jButtonOrtografiaMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Materias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Materias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Materias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Materias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Materias dialog = new Materias(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlimentacion;
    private javax.swing.JButton jButtonAtras;
    private javax.swing.JButton jButtonEcosistemas;
    private javax.swing.JButton jButtonGlosario;
    private javax.swing.JButton jButtonMascota;
    private javax.swing.JButton jButtonNacimiento;
    private javax.swing.JButton jButtonOraciones;
    private javax.swing.JButton jButtonOrtografia;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabelBiologia;
    private javax.swing.JLabel jLabelEspaniol;
    private javax.swing.JLabel jLabelMasc;
    private javax.swing.JLabel jLabelMascota;
    private javax.swing.JLabel jLabelTitulo;
    // End of variables declaration//GEN-END:variables
}
