lista=[]
print("Dame 10 números")
n1=int(input("1-"))
lista.append(n1)
n2=int(input("2-"))
lista.append(n2)
n3=int(input("3-"))
lista.append(n3)
n4=int(input("4-"))
lista.append(n4)
n5=int(input("5-"))
lista.append(n5)
n6=int(input("6-"))
lista.append(n6)
n7=int(input("7-"))
lista.append(n7)
n8=int(input("8-"))
lista.append(n8)
n9=int(input("9-"))
lista.append(n9)
n10=int(input("10-"))
lista.append(n10)
print(lista)
lista.sort()
print("Lista ordenada:",lista)
